language: node_js

node_js:
  - "4"
  - "5"
  - "6"

services:
  - mongodb

before_script:
  - "npm install --dev"
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

notifications:
  email: false
